# Generated by Django 3.1.2 on 2020-10-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(max_length=1000)),
                ('attack_type', models.CharField(max_length=200)),
                ('output_string', models.CharField(max_length=1000)),
            ],
        ),
    ]
