# Generated by Django 3.1.3 on 2020-11-18 01:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cached_key', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('input_string', models.CharField(max_length=1000)),
                ('input_histogram', models.CharField(default='[]', max_length=1000)),
                ('input_label', models.CharField(max_length=5)),
                ('model_name', models.CharField(max_length=200)),
                ('recipe_name', models.CharField(max_length=200)),
                ('output_string', models.CharField(max_length=1000)),
                ('output_label', models.CharField(max_length=5)),
                ('output_histogram', models.CharField(default='[]', max_length=1000)),
            ],
        ),
    ]
