# Generated by Django 3.1.3 on 2020-11-04 01:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attackresult',
            name='raw_output',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(default=0), default=0, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attackresult',
            name='score',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
