# Generated by Django 3.1.3 on 2020-11-04 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdemo', '0002_auto_20201103_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attackresult',
            name='raw_output',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
