# Generated by Django 3.1.3 on 2020-11-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdemo', '0003_auto_20201103_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackresult',
            name='attack_type',
        ),
        migrations.AddField(
            model_name='attackresult',
            name='model_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attackresult',
            name='recipe_name',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
