# Generated by Django 3.1.3 on 2020-11-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdemo', '0004_auto_20201103_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attackresult',
            name='raw_output',
        ),
        migrations.RemoveField(
            model_name='attackresult',
            name='score',
        ),
        migrations.AddField(
            model_name='attackresult',
            name='input_histogram',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='attackresult',
            name='output_histogram',
            field=models.CharField(default='[]', max_length=1000),
        ),
    ]
